#! /bin/sh


## AUTOSTART ##
sxhkd &
picom &
dunst &
flameshot &
thunar --daemon &
$HOME/.config/polybar/launch.sh &
feh --bg-scale ~/Pictures/Wallpapers/winter-mountain.jpg ~/Pictures/Wallpapers/winter-mountain.jpg &


## MONITORS ##
bspc monitor DP-4 -d I II III IV 
bspc monitor DP-0 -d V VI VII VIII


## BSPWM CONFIG ##
bspc config border_width                  4
bspc config window_gap                    10
bspc config top_padding                   20
bspc config bottom_padding                0
bspc config left_padding                  0
bspc config right_padding                 0
bspc config single_monocle                false
bspc config click_to_focus                true
bspc config split_ratio                   0.50
bspc config borderless_monocle            true
bspc config gapless_monocle               true
bspc config focus_by_distance             true
bspc config focus_follows_pointer         true
bspc config history_aware_focus           true
bspc config remove_disabled_monitors      true
bspc config merge_overlapping_monitors    true
bspc config pointer_modifier mod4
bspc config pointer_action1 move
bspc config pointer_action2 resize_side
bspc config pointer_action3 resize_corner


## BSPWM COLORS ##
bspc config normal_border_color		      "#2e3440"
bspc config focused_border_color	      "#f2f2f2"


## BSPWM RULES ##
bspc rule -a Gimp desktop='^8' state=floating follow=on
bspc rule -a Chromium desktop='^2'
bspc rule -a mplayer2 state=floating
bspc rule -a Kupfer.py focus=on
bspc rule -a Screenkey manage=off
